name: End2End Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'tests/**'
      - 'tools/**'
      - '.github/workflows/end2end_tests.yaml'
      - 'requirements*.txt'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_tests:
    name: E2E Tests on ${{ matrix.os }} / Python ${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        version: ['3.10']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.sha }}
        submodules: recursive  # Ensures submodules are cloned

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}
        cache: pip

    - name: Install dependencies
      shell: bash
      run: |
        CONSTRAINTS_FILE="$GITHUB_WORKSPACE/constraints.txt"
        echo "setuptools<82" > "$CONSTRAINTS_FILE"
        export PIP_CONSTRAINT="$CONSTRAINTS_FILE"
        pip install -e .[dev]

    - name: Run tests
      run: pytest tests/test_end2end.py --download-weights --delete-weights-now -s -v

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        create_credentials_file: true
        export_environment_variables: true

    - name: Run private model tests
      if: github.event.pull_request.head.repo.full_name == github.repository
      run: pytest tests/test_end2end.py::test_private_model_conversion --test-private --delete-weights-now -s -v
